### ISSUE TITLE
Your stack restriction

### ISSUE THREAD

**Issue by raszia** [mehrandvd/general-stack#12]
Thanks for sharing your information with us.
It seems to me you are restricted yourself to frameworks and to OS, i don't like frameworks specially in backend, and in embedded systems. they gonna make lot of trouble in embedded systems.
in theory .net may run on Linux, in practice its not a pleasant experience. I did it once, I don’t want to do it ever again. debugging .net in Linux is so painful.
don't depend your future to others. by choosing frameworks you are depended to a group of programmers who you don't know. they gonna drag you wherever they want.
that's my opinion

**Comment by mehrandvd** [comment]
Thank you for your detailed opinion.
What do you mean by running .NET on Linux? Do you mean .NET Framework or .NET Core? Because they're totally different products.
Interesting to know, that currently the best performance of .NET Core is not on Windows! According to [TechEmpower Benchkamarks](https://www.techempower.com/benchmarks/) its best performance is when its running on linux!
So .NET Core is not something that is "ported on linux". It is developed on linux, for linux!

The other main difference between .NET Core and .NET Framework is that .NET Core is being completely developed on GitHub! So it is completely open source and "they" are not able to "drag us wherever they want!".

**Comment by raszia** [comment]
You are right about .net core in Linux that was my mistake i didn't read documents carefully. but it's still a framework, even if it's opensource. it's a FRAME for your works!!! ,you must do your things in a FRAME guess who's FRAME? THEM. you cannot commit any change without their permission on git hub, any change must be in the there FRAME. the link that you provide to me is a compression for frameworks and as i said before i don't like frameworks and i don't care about their performance. if you get a fork from the project and change the source code for your own purpose it's not .net core framework anymore and that's exactly my point. make your own framework for your own purpose, don't use general purpose frameworks.

**Comment by mehrandvd** [comment]
Ahh.. I see. You're totally against using frameworks. Yes.. That's completely different approach than mine. It has lots of benefits like you are not in any FRAME that is created by THEM. So I am in full control of what I'm making. I understand this approach.

The reason I'm not taking this approach is that I don't believe that I can create a better frame in most cases! For example, if I decide not to use a framework like Angular or React, I should create one by myself. That's good as I will not work in a FRAME created by others. Instead I will create my own FRAME and I'm sure I can change it whenever I like. The problem is that I am not sure about my frame being a better frame than others! In most cases I trust to the frames created by other professionals that are expert in creating those frames. I feel more secure living in their frames, unless in situations I feel that I'm better.

So, although I understand the benefits of your approach, I feel more secure and comfortable using some proof frameworks and stick to their frames.

**Comment by raszia** [comment]
I am hundred percent sure you are in full control of what you have made and what you gonna make, i wish you best. and again thanks for this conversation and information.
Good Luck!
